// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScannerFinalPDF.Model.Data;

namespace ScannerFinalPDF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231206093319_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Maket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Colotp")
                        .HasColumnType("int");

                    b.Property<int>("Colstr")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Fill")
                        .HasColumnType("int");

                    b.Property<int?>("IdZayvkiId")
                        .HasColumnType("int");

                    b.Property<double>("Kvadr")
                        .HasColumnType("float");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdZayvkiId");

                    b.ToTable("Maket");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MaketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RSId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaketId");

                    b.HasIndex("RSId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.RS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaketId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int?>("RSId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaketId");

                    b.HasIndex("RSId");

                    b.ToTable("RS");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Sroki", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Coldn")
                        .HasColumnType("int");

                    b.Property<int?>("MaketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RSId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("MaketId");

                    b.HasIndex("RSId");

                    b.ToTable("Sroki");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_rozh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaketId")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<int?>("RSId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("MaketId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RSId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Zayvka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commentz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDostav")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePlanov")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePriem")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaketId")
                        .HasColumnType("int");

                    b.Property<int>("NShop")
                        .HasColumnType("int");

                    b.Property<string>("NameRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberTruck")
                        .HasColumnType("int");

                    b.Property<int?>("RsId")
                        .HasColumnType("int");

                    b.Property<int?>("Sotrid")
                        .HasColumnType("int");

                    b.Property<int?>("Srokiid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaketId");

                    b.HasIndex("RsId");

                    b.HasIndex("Sotrid");

                    b.HasIndex("Srokiid");

                    b.HasIndex("Usersid");

                    b.ToTable("Zayvka");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Maket", b =>
                {
                    b.HasOne("ScannerFinalPDF.Model.Data.Zayvka", "IdZayvki")
                        .WithMany()
                        .HasForeignKey("IdZayvkiId");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Position", b =>
                {
                    b.HasOne("ScannerFinalPDF.Model.Data.Maket", null)
                        .WithMany("AllPos")
                        .HasForeignKey("MaketId");

                    b.HasOne("ScannerFinalPDF.Model.Data.RS", null)
                        .WithMany("AllPos")
                        .HasForeignKey("RSId");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.RS", b =>
                {
                    b.HasOne("ScannerFinalPDF.Model.Data.Maket", null)
                        .WithMany("AllRs")
                        .HasForeignKey("MaketId");

                    b.HasOne("ScannerFinalPDF.Model.Data.RS", null)
                        .WithMany("AllRs")
                        .HasForeignKey("RSId");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Sroki", b =>
                {
                    b.HasOne("ScannerFinalPDF.Model.Data.Maket", null)
                        .WithMany("AllSroki")
                        .HasForeignKey("MaketId");

                    b.HasOne("ScannerFinalPDF.Model.Data.RS", null)
                        .WithMany("AllSroki")
                        .HasForeignKey("RSId");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.User", b =>
                {
                    b.HasOne("ScannerFinalPDF.Model.Data.Maket", null)
                        .WithMany("AllUsers")
                        .HasForeignKey("MaketId");

                    b.HasOne("ScannerFinalPDF.Model.Data.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");

                    b.HasOne("ScannerFinalPDF.Model.Data.RS", null)
                        .WithMany("AllUsers")
                        .HasForeignKey("RSId");
                });

            modelBuilder.Entity("ScannerFinalPDF.Model.Data.Zayvka", b =>
                {
                    b.HasOne("ScannerFinalPDF.Model.Data.Maket", null)
                        .WithMany("AllZayvki")
                        .HasForeignKey("MaketId");

                    b.HasOne("ScannerFinalPDF.Model.Data.RS", "Rs")
                        .WithMany("AllZayvki")
                        .HasForeignKey("RsId");

                    b.HasOne("ScannerFinalPDF.Model.Data.User", "Sotr")
                        .WithMany()
                        .HasForeignKey("Sotrid");

                    b.HasOne("ScannerFinalPDF.Model.Data.Sroki", "Sroki")
                        .WithMany()
                        .HasForeignKey("Srokiid");

                    b.HasOne("ScannerFinalPDF.Model.Data.User", "Users")
                        .WithMany()
                        .HasForeignKey("Usersid");
                });
#pragma warning restore 612, 618
        }
    }
}
